<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.2 setup script
 * Date: Tue, 11 Jul 2017 00:49:00 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'senha';

/* End of servers configuration */

$cfg['blowfish_secret'] = '*\'Zc5-rL`B_,~KNoEW+t&V#7Cs,_Ui8K';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>